import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Check, Mail, User, Lock } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Logo } from "@/components/mentor/Logo";

export const Route = createFileRoute("/cadastro")({ component: CadastroPage });
const benefits = ["Plano personalizado de carreira", "Recomendações baseadas em IA", "Acompanhamento da sua evolução"];
function CadastroPage() { const navigate = useNavigate(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); return <main className="min-h-screen bg-background lg:grid lg:grid-cols-2"><section className="hidden bg-gradient-ai p-10 text-primary-foreground lg:flex lg:flex-col lg:justify-between"><Logo/><div className="max-w-lg"><p className="text-sm font-semibold text-primary-foreground/70">COMECE SUA JORNADA</p><h1 className="mt-3 text-4xl font-semibold leading-tight">Um plano claro para o próximo capítulo da sua carreira.</h1><div className="mt-8 space-y-4">{benefits.map(x=><div key={x} className="flex items-center gap-3"><span className="flex size-7 items-center justify-center rounded-full bg-primary-foreground/15"><Check className="size-4"/></span><span>{x}</span></div>)}</div></div><p className="text-sm text-primary-foreground/60">Mentor AI · Requalificação profissional</p></section><section className="flex min-h-screen items-center justify-center px-5 py-10"><div className="w-full max-w-md"><div className="lg:hidden"><Logo/></div><div className="mt-10 lg:mt-0"><p className="text-sm font-semibold text-primary">Crie sua conta</p><h2 className="mt-2 text-3xl font-semibold">Vamos começar?</h2><p className="mt-2 text-sm text-muted-foreground">Leva poucos minutos para configurar seu perfil.</p></div><form className="mt-8 space-y-4" onSubmit={e=>{e.preventDefault();navigate({to:"/onboarding"})}}><div className="space-y-2"><Label>Nome</Label><div className="relative"><User className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-10" value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome" required/></div></div><div className="space-y-2"><Label>Email</Label><div className="relative"><Mail className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-10" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@email.com" required/></div></div><div className="space-y-2"><Label>Senha</Label><div className="relative"><Lock className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-10" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo de 8 caracteres" required minLength={8}/></div></div><label className="flex gap-2 text-xs text-muted-foreground"><input type="checkbox" required className="mt-0.5"/> Concordo com os termos de uso e política de privacidade.</label><Button className="w-full" size="lg">Criar minha conta <ArrowRight className="size-4"/></Button></form><p className="mt-7 text-center text-sm text-muted-foreground">Já possui uma conta? <Link to="/login" className="font-semibold text-primary">Entrar</Link></p></div></section></main> }
