import { useState, type ReactNode } from "react";
import { Link, useRouter } from "@tanstack/react-router";
import { BarChart3, LayoutDashboard, LogOut, Menu, Route as RouteIcon, Sparkles, User, X } from "lucide-react";
import { Logo } from "./Logo";
import { Button } from "@/components/ui/button";
import { useMentor } from "@/lib/mentor/store";
import { clearAuth } from "@/lib/api";
const nav=[{to:"/dashboard",label:"Dashboard",icon:LayoutDashboard},{to:"/plano",label:"Meu Plano",icon:RouteIcon},{to:"/mentor-ai",label:"Mentor AI",icon:Sparkles},{to:"/progresso",label:"Progresso",icon:BarChart3},{to:"/perfil",label:"Meu Perfil",icon:User}] as const;
function NavLinks({onNavigate}:{onNavigate?:()=>void}){return <nav className="flex flex-col gap-1">{nav.map(({to,label,icon:Icon})=><Link key={to} to={to} onClick={onNavigate} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-sidebar-foreground/80 transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground" activeProps={{className:"bg-sidebar-accent text-sidebar-accent-foreground font-semibold hover:bg-sidebar-accent"}}><Icon className="size-4.5"/>{label}</Link>)}</nav>}
function UserBlock(){const{profile}=useMentor();const router=useRouter();const logout=()=>{clearAuth();router.navigate({to:"/login"});};return <div className="border-t border-sidebar-border pt-4"><div className="flex items-center gap-3 rounded-xl px-3 py-2"><span className="bg-gradient-ai flex size-9 items-center justify-center rounded-full text-sm font-semibold text-primary-foreground">{profile.name.charAt(0)}</span><div className="min-w-0"><p className="truncate text-sm font-medium">{profile.name}</p><p className="truncate text-xs text-muted-foreground">{profile.email}</p></div></div><button onClick={logout} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-muted-foreground transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"><LogOut className="size-4.5"/> Sair da conta</button></div>}
export function AppShell({children}:{children:ReactNode}){const[open,setOpen]=useState(false);const router=useRouter();const path=router.state.location.pathname;const currentLabel=nav.find(item=>path.startsWith(item.to))?.label??"Dashboard";return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col border-r border-sidebar-border bg-sidebar px-4 py-6 lg:flex"><Logo to="/dashboard" className="px-2"/><div className="mt-8 flex-1"><p className="px-3 pb-2 text-xs font-semibold tracking-wider text-muted-foreground uppercase">Sua jornada</p><NavLinks/></div><UserBlock/></aside><header className="sticky top-0 z-30 flex items-center justify-between gap-3 border-b border-border bg-background/80 px-4 py-3 backdrop-blur-md lg:hidden"><Logo to="/dashboard"/><Button variant="ghost" size="icon" aria-label="Abrir menu" onClick={()=>setOpen(v=>!v)}>{open?<X className="size-5"/>:<Menu className="size-5"/>}</Button></header>{open&&<div className="fixed inset-x-0 top-[57px] bottom-0 z-30 animate-rise-in bg-sidebar px-4 py-5 lg:hidden"><NavLinks onNavigate={()=>setOpen(false)}/><div className="mt-6"><UserBlock/></div></div>}<main className="lg:pl-64"><div className="hidden items-center gap-2 border-b border-border px-8 py-4 text-sm text-muted-foreground lg:flex"><span>Mentor AI</span><span>/</span><span className="font-medium text-foreground">{currentLabel}</span></div><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10">{children}</div></main></div>}
