/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorAiRouteImport } from './routes/mentor-ai'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as ProgressoRouteImport } from './routes/progresso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAiRoute = MentorAiRouteImport.update({
  id: '/mentor-ai',
  path: '/mentor-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mentor-ai': typeof MentorAiRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mentor-ai': typeof MentorAiRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mentor-ai': typeof MentorAiRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/mentor-ai'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/progresso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/mentor-ai'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/progresso'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/mentor-ai'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/progresso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MentorAiRoute: typeof MentorAiRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PlanoRoute: typeof PlanoRoute
  ProgressoRoute: typeof ProgressoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-ai': {
      id: '/mentor-ai'
      path: '/mentor-ai'
      fullPath: '/mentor-ai'
      preLoaderRoute: typeof MentorAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MentorAiRoute: MentorAiRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PlanoRoute: PlanoRoute,
  ProgressoRoute: ProgressoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
