/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as MentorAiRouteImport } from './routes/mentor-ai'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const CadastroRoute = CadastroRouteImport.update({ id: '/cadastro', path: '/cadastro', getParentRoute: () => rootRouteImport } as any)
const OnboardingRoute = OnboardingRouteImport.update({ id: '/onboarding', path: '/onboarding', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const PlanoRoute = PlanoRouteImport.update({ id: '/plano', path: '/plano', getParentRoute: () => rootRouteImport } as any)
const MentorAiRoute = MentorAiRouteImport.update({ id: '/mentor-ai', path: '/mentor-ai', getParentRoute: () => rootRouteImport } as any)
const ProgressoRoute = ProgressoRouteImport.update({ id: '/progresso', path: '/progresso', getParentRoute: () => rootRouteImport } as any)
const PerfilRoute = PerfilRouteImport.update({ id: '/perfil', path: '/perfil', getParentRoute: () => rootRouteImport } as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({ id: '/configuracoes', path: '/configuracoes', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastro': typeof CadastroRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof DashboardRoute
  '/plano': typeof PlanoRoute
  '/mentor-ai': typeof MentorAiRoute
  '/progresso': typeof ProgressoRoute
  '/perfil': typeof PerfilRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastro': typeof CadastroRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof DashboardRoute
  '/plano': typeof PlanoRoute
  '/mentor-ai': typeof MentorAiRoute
  '/progresso': typeof ProgressoRoute
  '/perfil': typeof PerfilRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CadastroRoute: typeof CadastroRoute
  OnboardingRoute: typeof OnboardingRoute
  DashboardRoute: typeof DashboardRoute
  PlanoRoute: typeof PlanoRoute
  MentorAiRoute: typeof MentorAiRoute
  ProgressoRoute: typeof ProgressoRoute
  PerfilRoute: typeof PerfilRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/cadastro': { id: '/cadastro'; path: '/cadastro'; fullPath: '/cadastro'; preLoaderRoute: typeof CadastroRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding': { id: '/onboarding'; path: '/onboarding'; fullPath: '/onboarding'; preLoaderRoute: typeof OnboardingRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/plano': { id: '/plano'; path: '/plano'; fullPath: '/plano'; preLoaderRoute: typeof PlanoRouteImport; parentRoute: typeof rootRouteImport }
    '/mentor-ai': { id: '/mentor-ai'; path: '/mentor-ai'; fullPath: '/mentor-ai'; preLoaderRoute: typeof MentorAiRouteImport; parentRoute: typeof rootRouteImport }
    '/progresso': { id: '/progresso'; path: '/progresso'; fullPath: '/progresso'; preLoaderRoute: typeof ProgressoRouteImport; parentRoute: typeof rootRouteImport }
    '/perfil': { id: '/perfil'; path: '/perfil'; fullPath: '/perfil'; preLoaderRoute: typeof PerfilRouteImport; parentRoute: typeof rootRouteImport }
    '/configuracoes': { id: '/configuracoes'; path: '/configuracoes'; fullPath: '/configuracoes'; preLoaderRoute: typeof ConfiguracoesRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = { IndexRoute, LoginRoute, CadastroRoute, OnboardingRoute, DashboardRoute, PlanoRoute, MentorAiRoute, ProgressoRoute, PerfilRoute, ConfiguracoesRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
